#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : paho.mqtt.cpp
Version  : 1.0.0
Release  : 1
URL      : https://github.com/eclipse/paho.mqtt.cpp/archive/v1.0.0.tar.gz
Source0  : https://github.com/eclipse/paho.mqtt.cpp/archive/v1.0.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause EPL-1.0
Requires: paho.mqtt.cpp-lib = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : cppunit-dev
BuildRequires : paho.mqtt.c-dev
Patch1: 0001-Make-lib-symlinks-relative.patch
Patch2: 0002-Use-usr-lib64.patch

%description
Fix the problem
aclocal: error: couldn't open directory 'm4': No such file or directory

%package dev
Summary: dev components for the paho.mqtt.cpp package.
Group: Development
Requires: paho.mqtt.cpp-lib = %{version}-%{release}
Provides: paho.mqtt.cpp-devel = %{version}-%{release}

%description dev
dev components for the paho.mqtt.cpp package.


%package lib
Summary: lib components for the paho.mqtt.cpp package.
Group: Libraries

%description lib
lib components for the paho.mqtt.cpp package.


%prep
%setup -q -n paho.mqtt.cpp-1.0.0
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537996478
make  %{?_smp_mflags} prefix=/usr PAHO_C_LIB_DIR=${RPM_BUILD_ROOT}/usr/lib PAHO_C_INC_DIR=${RPM_BUILD_ROOT}/usr/include

%install
export SOURCE_DATE_EPOCH=1537996478
rm -rf %{buildroot}
%make_install prefix=/usr PAHO_C_LIB_DIR=${RPM_BUILD_ROOT}/usr/lib PAHO_C_INC_DIR=${RPM_BUILD_ROOT}/usr/include

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/mqtt/async_client.h
/usr/include/mqtt/buffer_ref.h
/usr/include/mqtt/buffer_view.h
/usr/include/mqtt/callback.h
/usr/include/mqtt/client.h
/usr/include/mqtt/connect_options.h
/usr/include/mqtt/delivery_token.h
/usr/include/mqtt/disconnect_options.h
/usr/include/mqtt/exception.h
/usr/include/mqtt/iaction_listener.h
/usr/include/mqtt/iasync_client.h
/usr/include/mqtt/iclient_persistence.h
/usr/include/mqtt/message.h
/usr/include/mqtt/response_options.h
/usr/include/mqtt/ssl_options.h
/usr/include/mqtt/string_collection.h
/usr/include/mqtt/thread_queue.h
/usr/include/mqtt/token.h
/usr/include/mqtt/topic.h
/usr/include/mqtt/types.h
/usr/include/mqtt/will_options.h
/usr/lib64/libpaho-mqttpp3.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpaho-mqttpp3.so.1
/usr/lib64/libpaho-mqttpp3.so.1.0.0
